export const tabs = [
  { id: "FUTURE", label: "Long-term", icon: "L" },
  { id: "YEARLY", label: "Yearly", icon: "Y" },
  { id: "MONTHLY", label: "Monthly", icon: "M" },
  { id: "WEEKLY", label: "Weekly", icon: "W" },
  { id: "DAILY", label: "Daily", icon: "D" },
  { id: "JOURNAL", label: "Journal", icon: "J" },
];

export const DEFAULT_TIMELINE_RANGE = { start: 5, end: 24 };
export const timelineHourOptions = Array.from({ length: 25 }, (_, index) => {
  return `${String(index).padStart(2, "0")}:00`;
});

export const themes = [
  {
    id: "sage-graphite-light",
    mode: "light",
    name: "Sage Graphite",
    description: "Sage / Graphite",
    primary: "#3F6256",
    secondary: "#8BAE9B",
    background: "#F7F9F7",
    css: {
      "--color-bg": "#F7F9F7",
      "--color-bg-rgb": "247 249 247",
      "--color-surface": "#FFFFFF",
      "--color-surface-muted": "#F1F5F2",
      "--color-panel": "#FFFFFF",
      "--color-sidebar": "#EEF3EF",
      "--color-sidebar-text": "#34433C",
      "--color-text": "#1D2622",
      "--color-muted": "#66736D",
      "--color-subtle": "#9AA7A0",
      "--color-border": "#D8E1DC",
      "--color-border-strong": "#B7C5BD",
      "--color-primary": "#3F6256",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#E3ECE7",
      "--color-secondary": "#8BAE9B",
      "--color-secondary-soft": "#EDF5F0",
      "--color-input": "#FFFFFF",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(29 38 34 / 4%)",
    },
  },
  {
    id: "mist-blue-light",
    mode: "light",
    name: "Mist Blue",
    description: "Mist / Steel Blue",
    primary: "#3F5F8A",
    secondary: "#77A6B6",
    background: "#F7F9FC",
    css: {
      "--color-bg": "#F7F9FC",
      "--color-bg-rgb": "247 249 252",
      "--color-surface": "#FFFFFF",
      "--color-surface-muted": "#F1F4F8",
      "--color-panel": "#FFFFFF",
      "--color-sidebar": "#EEF3F8",
      "--color-sidebar-text": "#344254",
      "--color-text": "#172033",
      "--color-muted": "#68758A",
      "--color-subtle": "#9AA7B8",
      "--color-border": "#D8E0EA",
      "--color-border-strong": "#B8C5D4",
      "--color-primary": "#3F5F8A",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#E5EDF6",
      "--color-secondary": "#77A6B6",
      "--color-secondary-soft": "#E7F3F6",
      "--color-input": "#FFFFFF",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(23 32 51 / 4%)",
    },
  },
  {
    id: "ink-lavender-light",
    mode: "light",
    name: "Ink Lavender",
    description: "Ink / Muted Lavender",
    primary: "#5A5F8F",
    secondary: "#9AA7C8",
    background: "#F8F8FC",
    css: {
      "--color-bg": "#F8F8FC",
      "--color-bg-rgb": "248 248 252",
      "--color-surface": "#FFFFFF",
      "--color-surface-muted": "#F2F3FA",
      "--color-panel": "#FFFFFF",
      "--color-sidebar": "#F0F1F8",
      "--color-sidebar-text": "#41445F",
      "--color-text": "#202235",
      "--color-muted": "#6D7086",
      "--color-subtle": "#A0A3B8",
      "--color-border": "#DCDDEC",
      "--color-border-strong": "#BFC2D8",
      "--color-primary": "#5A5F8F",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#E8EAF5",
      "--color-secondary": "#9AA7C8",
      "--color-secondary-soft": "#EFF2FA",
      "--color-input": "#FFFFFF",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(32 34 53 / 4%)",
    },
  },
  {
    id: "linen-olive-light",
    mode: "light",
    name: "Linen Olive",
    description: "Linen / Olive",
    primary: "#6A6246",
    secondary: "#9AA17A",
    background: "#FAF7EF",
    css: {
      "--color-bg": "#FAF7EF",
      "--color-bg-rgb": "250 247 239",
      "--color-surface": "#FFFDF8",
      "--color-surface-muted": "#F4EEE2",
      "--color-panel": "#FFFDF8",
      "--color-sidebar": "#F1EBDD",
      "--color-sidebar-text": "#514B39",
      "--color-text": "#2B261E",
      "--color-muted": "#746C5B",
      "--color-subtle": "#A89F8E",
      "--color-border": "#E2D8C6",
      "--color-border-strong": "#C8B99F",
      "--color-primary": "#6A6246",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#ECE5D4",
      "--color-secondary": "#9AA17A",
      "--color-secondary-soft": "#F0F1E4",
      "--color-input": "#FFFDF8",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(43 38 30 / 5%)",
    },
  },
  {
    id: "graphite-blue-dark",
    mode: "dark",
    name: "Graphite Blue",
    description: "Graphite / Blue",
    primary: "#96B1FF",
    secondary: "#94A5D0",
    background: "#101218",
    css: {
      "--color-bg": "#101218",
      "--color-bg-rgb": "16 18 24",
      "--color-surface": "#191C24",
      "--color-surface-muted": "#222631",
      "--color-panel": "#171A21",
      "--color-sidebar": "#13161C",
      "--color-sidebar-text": "#D5DBE8",
      "--color-text": "#EBEEF5",
      "--color-muted": "#A4ADBE",
      "--color-subtle": "#8993A6",
      "--color-border": "#303644",
      "--color-border-strong": "#465063",
      "--color-primary": "#96B1FF",
      "--color-primary-text": "#101522",
      "--color-primary-soft": "#222D48",
      "--color-secondary": "#94A5D0",
      "--color-secondary-soft": "#242A39",
      "--color-input": "#1C2029",
      "--color-danger": "#FF929D",
      "--color-danger-soft": "#39232B",
      "--shadow-panel": "0 1px 3px rgb(0 0 0 / 22%)",
    },
  },
  {
    id: "taupe-linen-dark",
    mode: "dark",
    name: "Taupe Linen",
    description: "Taupe / Beige",
    primary: "#D7C5AF",
    secondary: "#B9ADA0",
    background: "#151413",
    css: {
      "--color-bg": "#151413",
      "--color-bg-rgb": "21 20 19",
      "--color-surface": "#201E1C",
      "--color-surface-muted": "#292623",
      "--color-panel": "#1C1A18",
      "--color-sidebar": "#181614",
      "--color-sidebar-text": "#DDD8D2",
      "--color-text": "#F0ECE7",
      "--color-muted": "#B1A99F",
      "--color-subtle": "#958D84",
      "--color-border": "#39342E",
      "--color-border-strong": "#50483F",
      "--color-primary": "#D7C5AF",
      "--color-primary-text": "#211B15",
      "--color-primary-soft": "#332C25",
      "--color-secondary": "#B9ADA0",
      "--color-secondary-soft": "#2B2621",
      "--color-input": "#23201D",
      "--color-danger": "#FF999D",
      "--color-danger-soft": "#3B2528",
      "--shadow-panel": "0 1px 3px rgb(0 0 0 / 22%)",
    },
  },
  {
    id: "forest-ink-dark",
    mode: "dark",
    name: "Forest Ink",
    description: "Forest / Ink",
    primary: "#93D9B5",
    secondary: "#9DBDB0",
    background: "#101615",
    css: {
      "--color-bg": "#101615",
      "--color-bg-rgb": "16 22 21",
      "--color-surface": "#192220",
      "--color-surface-muted": "#222D29",
      "--color-panel": "#161E1B",
      "--color-sidebar": "#121A17",
      "--color-sidebar-text": "#D4E4DC",
      "--color-text": "#EAF3EE",
      "--color-muted": "#A1B5AA",
      "--color-subtle": "#879F92",
      "--color-border": "#2E3D35",
      "--color-border-strong": "#43584B",
      "--color-primary": "#93D9B5",
      "--color-primary-text": "#10251A",
      "--color-primary-soft": "#21392C",
      "--color-secondary": "#9DBDB0",
      "--color-secondary-soft": "#26352E",
      "--color-input": "#1C2722",
      "--color-danger": "#FF969F",
      "--color-danger-soft": "#3A252B",
      "--shadow-panel": "0 1px 3px rgb(0 0 0 / 22%)",
    },
  },
  {
    id: "mono-black-dark",
    mode: "dark",
    name: "Mono Black",
    description: "Black / Gray",
    primary: "#E2E2EA",
    secondary: "#B4B4C1",
    background: "#111113",
    css: {
      "--color-bg": "#111113",
      "--color-bg-rgb": "17 17 19",
      "--color-surface": "#1B1B1F",
      "--color-surface-muted": "#25252A",
      "--color-panel": "#18181B",
      "--color-sidebar": "#141417",
      "--color-sidebar-text": "#DCDCE3",
      "--color-text": "#EEEEF2",
      "--color-muted": "#AEAEB9",
      "--color-subtle": "#93939F",
      "--color-border": "#333339",
      "--color-border-strong": "#4A4A54",
      "--color-primary": "#E2E2EA",
      "--color-primary-text": "#19191D",
      "--color-primary-soft": "#303036",
      "--color-secondary": "#B4B4C1",
      "--color-secondary-soft": "#27272D",
      "--color-input": "#202024",
      "--color-danger": "#FF949D",
      "--color-danger-soft": "#38232A",
      "--shadow-panel": "0 1px 3px rgb(0 0 0 / 22%)",
    },
  },
];
