export const tabs = [
  { id: "FUTURE", label: "Long-term", icon: "L" },
  { id: "YEARLY", label: "Yearly", icon: "Y" },
  { id: "MONTHLY", label: "Monthly", icon: "M" },
  { id: "WEEKLY", label: "Weekly", icon: "W" },
  { id: "DAILY", label: "Daily", icon: "D" },
  { id: "JOURNAL", label: "Journal", icon: "J" },
];

export const DEFAULT_TIMELINE_RANGE = { start: 5, end: 24 };
export const timelineHourOptions = Array.from({ length: 25 }, (_, index) => {
  return `${String(index).padStart(2, "0")}:00`;
});

export const themes = [
  {
    id: "sage-graphite-light",
    mode: "light",
    name: "Sage Graphite",
    description: "Sage / Graphite",
    primary: "#3F6256",
    secondary: "#8BAE9B",
    background: "#F7F9F7",
    css: {
      "--color-bg": "#F7F9F7",
      "--color-bg-rgb": "247 249 247",
      "--color-surface": "#FFFFFF",
      "--color-surface-muted": "#F1F5F2",
      "--color-panel": "#FFFFFF",
      "--color-sidebar": "#EEF3EF",
      "--color-sidebar-text": "#34433C",
      "--color-text": "#1D2622",
      "--color-muted": "#66736D",
      "--color-subtle": "#9AA7A0",
      "--color-border": "#D8E1DC",
      "--color-border-strong": "#B7C5BD",
      "--color-primary": "#3F6256",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#E3ECE7",
      "--color-secondary": "#8BAE9B",
      "--color-secondary-soft": "#EDF5F0",
      "--color-input": "#FFFFFF",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(29 38 34 / 4%)",
    },
  },
  {
    id: "mist-blue-light",
    mode: "light",
    name: "Mist Blue",
    description: "Mist / Steel Blue",
    primary: "#3F5F8A",
    secondary: "#77A6B6",
    background: "#F7F9FC",
    css: {
      "--color-bg": "#F7F9FC",
      "--color-bg-rgb": "247 249 252",
      "--color-surface": "#FFFFFF",
      "--color-surface-muted": "#F1F4F8",
      "--color-panel": "#FFFFFF",
      "--color-sidebar": "#EEF3F8",
      "--color-sidebar-text": "#344254",
      "--color-text": "#172033",
      "--color-muted": "#68758A",
      "--color-subtle": "#9AA7B8",
      "--color-border": "#D8E0EA",
      "--color-border-strong": "#B8C5D4",
      "--color-primary": "#3F5F8A",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#E5EDF6",
      "--color-secondary": "#77A6B6",
      "--color-secondary-soft": "#E7F3F6",
      "--color-input": "#FFFFFF",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(23 32 51 / 4%)",
    },
  },
  {
    id: "ink-lavender-light",
    mode: "light",
    name: "Ink Lavender",
    description: "Ink / Muted Lavender",
    primary: "#5A5F8F",
    secondary: "#9AA7C8",
    background: "#F8F8FC",
    css: {
      "--color-bg": "#F8F8FC",
      "--color-bg-rgb": "248 248 252",
      "--color-surface": "#FFFFFF",
      "--color-surface-muted": "#F2F3FA",
      "--color-panel": "#FFFFFF",
      "--color-sidebar": "#F0F1F8",
      "--color-sidebar-text": "#41445F",
      "--color-text": "#202235",
      "--color-muted": "#6D7086",
      "--color-subtle": "#A0A3B8",
      "--color-border": "#DCDDEC",
      "--color-border-strong": "#BFC2D8",
      "--color-primary": "#5A5F8F",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#E8EAF5",
      "--color-secondary": "#9AA7C8",
      "--color-secondary-soft": "#EFF2FA",
      "--color-input": "#FFFFFF",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(32 34 53 / 4%)",
    },
  },
  {
    id: "linen-olive-light",
    mode: "light",
    name: "Linen Olive",
    description: "Linen / Olive",
    primary: "#6A6246",
    secondary: "#9AA17A",
    background: "#FAF7EF",
    css: {
      "--color-bg": "#FAF7EF",
      "--color-bg-rgb": "250 247 239",
      "--color-surface": "#FFFDF8",
      "--color-surface-muted": "#F4EEE2",
      "--color-panel": "#FFFDF8",
      "--color-sidebar": "#F1EBDD",
      "--color-sidebar-text": "#514B39",
      "--color-text": "#2B261E",
      "--color-muted": "#746C5B",
      "--color-subtle": "#A89F8E",
      "--color-border": "#E2D8C6",
      "--color-border-strong": "#C8B99F",
      "--color-primary": "#6A6246",
      "--color-primary-text": "#FFFFFF",
      "--color-primary-soft": "#ECE5D4",
      "--color-secondary": "#9AA17A",
      "--color-secondary-soft": "#F0F1E4",
      "--color-input": "#FFFDF8",
      "--color-danger": "#B4232A",
      "--color-danger-soft": "#FBE7E9",
      "--shadow-panel": "0 1px 2px rgb(43 38 30 / 5%)",
    },
  },
  {
    id: "graphite-blue-dark",
    mode: "dark",
    name: "Graphite Blue",
    description: "Graphite / Blue",
    primary: "#AFC3DD",
    secondary: "#86B8C6",
    background: "#181C22",
    css: {
      "--color-bg": "#181C22",
      "--color-bg-rgb": "24 28 34",
      "--color-surface": "#333A45",
      "--color-surface-muted": "#424B58",
      "--color-panel": "#242A33",
      "--color-sidebar": "#20262E",
      "--color-sidebar-text": "#E1E8EF",
      "--color-text": "#F2F5F8",
      "--color-muted": "#B9C2CC",
      "--color-subtle": "#98A5B4",
      "--color-border": "#566171",
      "--color-border-strong": "#717E90",
      "--color-primary": "#AFC3DD",
      "--color-primary-text": "#181C22",
      "--color-primary-soft": "#40506A",
      "--color-secondary": "#86B8C6",
      "--color-secondary-soft": "#36505B",
      "--color-input": "#39424E",
      "--color-danger": "#FCA5A5",
      "--color-danger-soft": "#563238",
      "--shadow-panel": "0 1px 2px rgb(0 0 0 / 18%)",
    },
  },
  {
    id: "taupe-linen-dark",
    mode: "dark",
    name: "Taupe Linen",
    description: "Taupe / Beige",
    primary: "#D7C8A8",
    secondary: "#BFA782",
    background: "#1F1C18",
    css: {
      "--color-bg": "#1F1C18",
      "--color-bg-rgb": "31 28 24",
      "--color-surface": "#3A342C",
      "--color-surface-muted": "#4A4237",
      "--color-panel": "#2A2621",
      "--color-sidebar": "#24211D",
      "--color-sidebar-text": "#E8DFCF",
      "--color-text": "#F4EEE5",
      "--color-muted": "#C7BDAE",
      "--color-subtle": "#A69A88",
      "--color-border": "#5B5246",
      "--color-border-strong": "#7A6E5D",
      "--color-primary": "#D7C8A8",
      "--color-primary-text": "#1F1C18",
      "--color-primary-soft": "#574B3B",
      "--color-secondary": "#BFA782",
      "--color-secondary-soft": "#4F4232",
      "--color-input": "#40382F",
      "--color-danger": "#FCA5A5",
      "--color-danger-soft": "#563238",
      "--shadow-panel": "0 1px 2px rgb(0 0 0 / 18%)",
    },
  },
  {
    id: "forest-ink-dark",
    mode: "dark",
    name: "Forest Ink",
    description: "Forest / Ink",
    primary: "#A9CDBD",
    secondary: "#8FAE9C",
    background: "#171D19",
    css: {
      "--color-bg": "#171D19",
      "--color-bg-rgb": "23 29 25",
      "--color-surface": "#333D36",
      "--color-surface-muted": "#424E46",
      "--color-panel": "#242D27",
      "--color-sidebar": "#202822",
      "--color-sidebar-text": "#E0EAE3",
      "--color-text": "#F0F5F1",
      "--color-muted": "#B8C5BD",
      "--color-subtle": "#9AAEA3",
      "--color-border": "#536358",
      "--color-border-strong": "#6F8276",
      "--color-primary": "#A9CDBD",
      "--color-primary-text": "#171D19",
      "--color-primary-soft": "#405848",
      "--color-secondary": "#8FAE9C",
      "--color-secondary-soft": "#3B5145",
      "--color-input": "#39443C",
      "--color-danger": "#FCA5A5",
      "--color-danger-soft": "#563238",
      "--shadow-panel": "0 1px 2px rgb(0 0 0 / 18%)",
    },
  },
  {
    id: "mono-black-dark",
    mode: "dark",
    name: "Mono Black",
    description: "Black / Gray",
    primary: "#E8E8E8",
    secondary: "#A8A8A8",
    background: "#101010",
    css: {
      "--color-bg": "#101010",
      "--color-bg-rgb": "16 16 16",
      "--color-surface": "#2D2D2D",
      "--color-surface-muted": "#3A3A3A",
      "--color-panel": "#1B1B1B",
      "--color-sidebar": "#171717",
      "--color-sidebar-text": "#EDEDED",
      "--color-text": "#F2F2F2",
      "--color-muted": "#C2C2C2",
      "--color-subtle": "#969696",
      "--color-border": "#4E4E4E",
      "--color-border-strong": "#707070",
      "--color-primary": "#E8E8E8",
      "--color-primary-text": "#111111",
      "--color-primary-soft": "#474747",
      "--color-secondary": "#A8A8A8",
      "--color-secondary-soft": "#343434",
      "--color-input": "#262626",
      "--color-danger": "#E6E6E6",
      "--color-danger-soft": "#3F3F3F",
      "--shadow-panel": "0 1px 2px rgb(0 0 0 / 28%)",
    },
  },
];
