export const state = {
  activeTab: "DAILY",
  sideTab: null,
  sidePanelOpen: false,
  isEditing: true,
  isLocked: false,
  dbReady: false,
  themeId: "sage-graphite-light",
  anchorDate: new Date(),
  tasks: {
    FUTURE: [],
    YEARLY: [],
    MONTHLY: [],
    WEEKLY: [],
    DAILY: [],
  },
  futureYearTasks: [],
  yearlyMonthTasks: [],
  monthDailyTasks: [],
  weekDailyTasks: [],
  journalEntries: [],
  timelineRanges: {},
  shouldAnimatePeriod: false,
  detailModal: null,
  selectedTaskId: null,
  pendingEditTaskId: null,
  copiedTaskBlock: null,
  collapsedSections: new Set(),
};
